server:
  port: 8094

spring:
  application:
    name: selenium
  # Config DB
  datasource:
    url: jdbc:mysql://localhost:3306/db_data?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: boot
    password: 1234
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  # Config Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  # Allow circular references
  main:
    allow-circular-references: false


webdriver:
  headless: true

logging:
  level:
    org.openqa.selenium: FATAL